CONNECT TO RCDB2;

CREATE TABLE EMP ( EMPNO int NOT NULL, FNAME VARCHAR(50) NULL, LNAME VARCHAR(50) NULL, JOB VARCHAR(50) NULL, MGR int NULL, HIREDATE date NULL, SAL double NULL, COMM double NULL, DEPT int NULL, PRIMARY KEY (EMPNO) );